### ISSUE TITLE
Limit who can cut releases

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/timestamp-authority#108]
**Description**

Currently, any time a tag is pushed, a release is cut. We need to review who has permission to push a tag (anyone with write or maintain? Or does it include triage?) and possibly restrict the list.

**Comment by cpanato** [comment]
anyone with write access can push tags

but we can define a tag rule and just persons with maintain and admin permissions can push it

https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role

**Comment by cpanato** [comment]
i can work on that and also replicate to the other projects

**Comment by haydentherapper** [comment]
Can we set up that restriction at the org level in the pulumi configuration? I assume we'd want this for all repos, might be worth checking with the TSC.

**Comment by haydentherapper** [comment]
Going to close this out as this is not just for this repo, but for any that use tag based releases
