### ISSUE TITLE
Could we release a container image?

### ISSUE THREAD

**Issue by vaikas** [sigstore/timestamp-authority#126]
**Description**

In order to bring in this to scaffolding:
https://github.com/sigstore/scaffolding/issues/450

And I'd expect that others would like a container also at some point, so it would be nice to get a container image released for this. I can work around this for now, but would be nice to get a released container.

**Comment by haydentherapper** [comment]
It’s uploaded to gchr https://github.com/sigstore/timestamp-authority/pkgs/container/timestamp-server

**Comment by cpanato** [comment]
we have both server and cli 
https://github.com/orgs/sigstore/packages?repo_name=timestamp-authority

closing as done, if is not that you want please let us know :)
