### ISSUE TITLE
Integrating with a NTP server

### ISSUE THREAD

**Issue by malancas** [sigstore/timestamp-authority#133]
**Description**

We should investigate the possibility of integrating the TSA with a NTP server. [CloudFlare offers a free NTP server](https://blog.cloudflare.com/secure-time/) as a possible option (credit to @haydentherapper for finding this). GCP also offers [NTP integration for its VMs](https://cloud.google.com/compute/docs/instances/configure-ntp).

In addition to providing a NTP server, the CloudFlare article also discusses an updated protocol based on NTP called NTS to communicate with the server. However, there does not seem to be Go support for the NTS protocol. There seem to be a few Go implementations of the NTP protocol on GitHub.

**Comment by kommendorkapten** [comment]
Nice, I was not aware of this issue.

I suggest we keep this PR https://github.com/sigstore/timestamp-authority/pull/143 as is, then continue to research state of NTS separately. Some more details on NTS: https://docs.ntpsec.org/latest/NTS-QuickStart.html

**Comment by kommendorkapten** [comment]
And also this: https://www.netnod.se/nts/network-time-security

**Comment by haydentherapper** [comment]
Agreed, let’s scope this issue to just NTP integration for your PR and we can follow up with another issue for NTS.

**Comment by haydentherapper** [comment]
Closing now that https://github.com/sigstore/timestamp-authority/pull/143 is done - We chatted about NTS and didn't see a benefit over NTP for monitoring.
