### ISSUE TITLE
Implement a mock client

### ISSUE THREAD

**Issue by hectorj2f** [sigstore/timestamp-authority#146]
**Description**

We need to create a mock client where all the different API calls are supported and these functions return `valid` data for testing purposes.

**Comment by haydentherapper** [comment]
Alternatively, a test server like I mentioned in https://github.com/sigstore/timestamp-authority/pull/143#discussion_r1021885303, though this is more heavyweight.

**Comment by haydentherapper** [comment]
This would be useful! FWIW, it's easy to spin up a local test server currently in unit testing, it's just more heavyweight.

**Comment by hectorj2f** [comment]
Yes, that is what I'd like to avoid with this mock client.

**Comment by haydentherapper** [comment]
We can probably start with having the client just replay a static certificate chain and response from a test instance. A mock client could also take in a signing key and chain and run parts of https://github.com/sigstore/timestamp-authority/blob/main/pkg/api/timestamp.go#L29

**Comment by haydentherapper** [comment]
Working on this
