### ISSUE TITLE
Default to NTP monitoring being on

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/timestamp-authority#164]
**Description**

I think this is a useful feature and we should change the flag to default to using the provided ntp monitor configuration.

cc @kommendorkapten

**Comment by kommendorkapten** [comment]
Totally agree!

**Comment by neilnaveen** [comment]
> **Description**
> 
> I think this is a useful feature and we should change the flag to default to using the provided ntp monitor configuration.
> 
> cc @kommendorkapten

I would like to work on this issue. What is expected in the default config? I am referring to https://github.com/sigstore/timestamp-authority/blob/25295ed8c2b807204f802584f786d4ee7bcc9f98/pkg/ntpmonitor/config.go#L26

**Comment by haydentherapper** [comment]
Thanks! We already have a default config (https://github.com/sigstore/timestamp-authority/blob/main/ntpsync.yaml).

**Comment by kommendorkapten** [comment]
What I think @haydentherapper is after is to change this logic: https://github.com/sigstore/timestamp-authority/blob/main/cmd/timestamp-server/app/serve.go#L84 to instead if require explicit activation via `--ntp-monitor` we should require explicit disabling like `--disable-ntp-monitor`. 

Maybe this was clear and I just misunderstood your comment @neilnaveen?
