### ISSUE TITLE
broken `--cert-chain` command line argument

### ISSUE THREAD

**Issue by bobcallaway** [sigstore/timestamp-authority#177]
**Description**

I started seeing CI failures, and it appears that the command line arg `--cert-chain` was renamed `--certificate-chain`

https://github.com/sigstore/scaffolding/actions/runs/3658333635/jobs/6182985071

I'm not sure how many clients are out there, but more of an FYI that this did (temporarily) break scaffolding CI runs

**Comment by haydentherapper** [comment]
Thanks for fixing this. Are these tests running from HEAD? Probably shouldn't be if so, we haven't cut a release with this changed flag yet.

**Comment by haydentherapper** [comment]
Filed issue
