### ISSUE TITLE
Adding malancas as maintainer

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/timestamp-authority#187]
**Description**

Meredith (@malancas) has done a lot of work on the timestamp authority, completing a [number of P0/P1 AIs](https://github.com/sigstore/timestamp-authority/issues?q=is%3Aissue+is%3Aclosed+assignee%3Amalancas+) to get a first release out, and driving the implementation of the verification library. Meredith has helped to review many PRs in this repo too. I'd like to propose Meredith as a maintainer for the repo.

cc @asraa for approval for other maintainers

**Comment by trevrosen** [comment]
🎉 Full support!

**Comment by asraa** [comment]
+1 !!

**Comment by haydentherapper** [comment]
Closing issue, opened the request in community! Congrats!
