### ISSUE TITLE
Signer hardcodes use of SHA-256

### ISSUE THREAD

**Issue by malancas** [sigstore/timestamp-authority#304]
**Description**

When a new crypto signer is created, the hash function is hardcoded to SHA-256. This can be found on the following lines:
- https://github.com/sigstore/timestamp-authority/blob/4121517967785c508dd57f3ea1a0d05c4692cfe9/pkg/signer/signer.go#L47
- https://github.com/sigstore/timestamp-authority/blob/4121517967785c508dd57f3ea1a0d05c4692cfe9/pkg/signer/signer.go#L42

The signer should accept a hash function configured when the server is created.

**Version**

**Comment by haydentherapper** [comment]
Something to investigate - How does ed25519 work with this, since it hardcodes its own hashing algorithm?
