### ISSUE TITLE
Add Recoverer middleware

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/timestamp-authority#38]
**Description**

https://github.com/go-chi/chi/blob/master/middleware/recoverer.go

Also review other middleware that's currently enabled

**Comment by malancas** [comment]
I'll take a look at this one as well.

**Comment by malancas** [comment]
@haydentherapper it looks like you already added the recoverer middleware a little while ago https://github.com/sigstore/timestamp-authority/blob/main/pkg/generated/restapi/configure_timestamp_server.go#L112

I can still review the already existing middleware in this issue though.
