### ISSUE TITLE
Address TODOs with package releases

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/timestamp-authority#50]
**Description**

**Comment by haydentherapper** [comment]
@cpanato, now that it's transferred, we should be good to address TODOs

**Comment by cpanato** [comment]
will do

**Comment by malancas** [comment]
@cpanato I'm happy to help set up anything around package releases. Let me know

**Comment by cpanato** [comment]
@malancas if you have time feel free to work on that :) that will be awesome

**Comment by haydentherapper** [comment]
@cpanato, what work was remaining? I see some TODOs in goreleaser, anything else?

**Comment by cpanato** [comment]
@haydentherapper do we want to publish the images in the gcr as well? or only in ghcr.io?

ok, give me 5 min then I will take a look at what is missing and fix that right away, sorry being extremely busy in the past weeks :(

**Comment by haydentherapper** [comment]
I think to just ghcr is totally reasonable, let's make it easy. I like the idea of making everything run by GHAs.

No worries!

**Comment by cpanato** [comment]
ok sounds good, in case we want in gcr later we can copy manually the old tags :)

I'm doing a rehearsal now and should be ready soon

**Comment by haydentherapper** [comment]
SG, happy to approve any PRs to update TODOs
