### ISSUE TITLE
Go through TODOs in generated code

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/timestamp-authority#80]
**Description**

**Comment by malancas** [comment]
Looking through the TODO functions in https://github.com/sigstore/timestamp-authority/blob/main/pkg/generated/restapi/configure_timestamp_server.go, the TODOs are around mostly server configuration.  I'm not sure there is any other configuration to add at the moment. Looking at the Rekor equivalent of this file, there aren't any configurations in Rekor that we are not currently using. Below is a breakdown of the TODOs:

- Configuring flags for API server options [here](https://github.com/sigstore/timestamp-authority/blob/main/pkg/generated/restapi/configure_timestamp_server.go#L41)
  - currently our server CLI arguments are accounted for in https://github.com/sigstore/timestamp-authority/blob/main/pkg/generated/restapi/server.go. Are there other flags you were thinking of setting?
- Swagger docs UI has been disabled [here](https://github.com/sigstore/timestamp-authority/blob/main/pkg/generated/restapi/configure_timestamp_server.go#L56). Is there a reason to keep this disabled?
- Configuring custom TLS is [here](https://github.com/sigstore/timestamp-authority/blob/main/pkg/generated/restapi/configure_timestamp_server.go#L79)
  - Rekor [does not set any custom TLS configurations](https://github.com/sigstore/rekor/blob/main/pkg/generated/restapi/configure_rekor_server.go#L160) either. Is there any kjind of custom configuration we wanted to start using across any of the components?
- Configuring server [here](https://github.com/sigstore/timestamp-authority/blob/main/pkg/generated/restapi/configure_timestamp_server.go#L87)
  - I don't think there's anything else we to configure here beyond the command line options already accounted for
- Setting up middleware [here](https://github.com/sigstore/timestamp-authority/blob/main/pkg/generated/restapi/configure_timestamp_server.go#L92)
	- This is for setting middleware for handler executors
	- All of our middleware is already accounted for in [setupGlobalMiddleware](https://github.com/sigstore/timestamp-authority/blob/main/pkg/generated/restapi/configure_timestamp_server.go#L92)
	- Following the comments on both of these functions, I think our middleware functionsshould remain in the function they are initialized in. Is there any other middleware we want to add?

I think these empty configuration functions can be left as is for now.

**Comment by haydentherapper** [comment]
> Are there other flags you were thinking of setting?

Nope, good as is!

> Swagger docs UI has been disabled [here](https://github.com/sigstore/timestamp-authority/blob/main/pkg/generated/restapi/configure_timestamp_server.go#L56). Is there a reason to keep this disabled?

We are hosting it on a separate endpoint (https://www.sigstore.dev/swagger/), so we should keep it disabled. I have added an issue to figure out how to hook up the swagger output here to this though

>  Is there any kjind of custom configuration we wanted to start using across any of the components?

No, we shouldn't support TLS for now, I think we should expect TLS termination is done via a proxy or ingress.

> I don't think there's anything else we to configure here beyond the command line options already accounted for

SGTM

> Setting up middleware [here](https://github.com/sigstore/timestamp-authority/blob/main/pkg/generated/restapi/configure_timestamp_server.go#L92)

Middleware LGTM

**Comment by haydentherapper** [comment]
So the only other TODO I found that's relevant is https://github.com/sigstore/timestamp-authority/blob/main/pkg/generated/client/timestamp/timestamp_client.go#L61 and https://github.com/sigstore/timestamp-authority/blob/main/pkg/generated/client/timestamp/timestamp_client.go#L98

However, I'm not sure how to fix those because they're in generated code. Also, there is nothing to validate - CertChain takes no params, and Response will fail if the request is not valid a asn1 timestamp request. So I think this issue should be good to close

**Comment by malancas** [comment]
Great, I'll go ahead and close it.
